services:

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db_data/mysql:/var/lib/mysql/
    environment:
      MYSQL_DATABASE: carservice
      MYSQL_USER: nabius
      MYSQL_PASSWORD: qwerty123456
      MYSQL_ROOT_PASSWORD: QWERTY123456

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: qwerty123456

  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    restart: always
    command:
      - --storageEngine
      - wiredTiger
      - --auth
    ports:
      - "27017:27017"
    environment:
#      - MONGO_INITDB_DATABASE = maintenance-db
      - MONGO_INITDB_ROOT_USERNAME = root
      - MONGO_INITDB_ROOT_PASSWORD = password
    volumes:
      - ./db_data/mongoDB:/var/lib/mongodb/data
    networks:
      - mongodb_network


  mongo-express:
    image: mongo-express:1.0.2-20
    container_name: mongo-express
    restart: always
    environment:
      ### MongoDB connection
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      ### MongoDB-Express WebUI
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_AUTH_USERNAME=admin
      - ME_CONFIG_MONGODB_AUTH_PASSWORD=password
      - ME_CONFIG_BASICAUTH=false
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=password
      - ME_CONFIG_OPTIONS_EDITORTHEME=dracula
    ports:
      - "28081:8081"
    networks:
      - mongodb_network
    depends_on:
      - mongo

networks:
  mongodb_network:
    driver: bridge
    name: mongo-network