spring:
  application:
    name: "Car service"
  profiles:
    active: "eng"
  datasource:
    url: jdbc:mysql://localhost:3306/carservice
    username: nabius
    password: qwerty123456
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true


  data:
    mongodb:
      uri: mongodb+srv://nabiusster:Artur2008@cluster0.fjqpr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      database: maintenances-db

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/realms/carservice
          jwk-set-uri: http://localhost:8083/realms/carservice/protocol/openid-connect/certs

      client:
        registration:
          keycloak:
            client-id: carservice

logging:
  level:
    org:
      springframework:
        security: trace