spring:
  application:
    name: Car service

data-reference:
  engine-types: бензиновий, дизельний, гібридний, електричний
  fuelTypes:
    - name: бензин
      brand: А-95,А-98,А-100
    - name: дізель
      brand: зимовий, літній, арктичний
    - name: електрика
      brand: